name: Publish Pre-release to npm

on:
  push:
    tags:
      - 'v*.*.*-alpha.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-rc.*'
      - 'v*.*.*-test.*'
      - 'v*.*.*-next.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Upgrade npm for Trusted Publishing
        run: npm install -g npm@latest

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint:check

      - name: Build
        run: yarn build

      - name: Extract pre-release tag
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          if [[ $TAG == *"-alpha."* ]]; then
            echo "dist_tag=alpha" >> $GITHUB_OUTPUT
          elif [[ $TAG == *"-beta."* ]]; then
            echo "dist_tag=beta" >> $GITHUB_OUTPUT
          elif [[ $TAG == *"-rc."* ]]; then
            echo "dist_tag=rc" >> $GITHUB_OUTPUT
          elif [[ $TAG == *"-test."* ]]; then
            echo "dist_tag=test" >> $GITHUB_OUTPUT
          elif [[ $TAG == *"-next."* ]]; then
            echo "dist_tag=next" >> $GITHUB_OUTPUT
          else
            echo "dist_tag=prerelease" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm with dist-tag
        run: npm publish --access public --tag ${{ steps.tag.outputs.dist_tag }}
